"""
https://school.programmers.co.kr/learn/courses/30/lessons/299310
연도별 대장균 크기의 편차 구하기
"""
WITH YEARLY_MAX AS (
    SELECT 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM 
        ECOLI_DATA
    GROUP BY 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
)
SELECT 
    EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) AS YEAR, (y.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV, e.ID
FROM 
    ECOLI_DATA e
JOIN 
    YEARLY_MAX y 
ON 
    EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY 
    YEAR, YEAR_DEV, e.ID;
